
public enum MessageType {
	WELCOME("WELCOME", MessageArg.MESS),
	HELP("HELP"),

	LISTE_DOMAINE("LISTE_DOMAINE", MessageArg.MESS),
	INFO_DOMAINE("INFO_DOMAINE"),

	NEW("NEW", MessageArg.PSEUDO, MessageArg.MDP ),
	NEW_SUCCESS("NEW_SUCCESS"),
	NEW_ERROR("NEW_ERROR"),

	CONNECT("CONNECT", MessageArg.PSEUDO, MessageArg.MDP, MessageArg.PORT ),
	CONNECT_SUCCESS("CONNECT_SUCCESS",MessageArg.PSEUDO, MessageArg.ADR, MessageArg.NB),
	CONNECT_ERROR("CONNECT_ERROR"),

	ADD_ANNONCE("ADD_ANNONCE", MessageArg.TITRE, MessageArg.DOMAINE, MessageArg.PRIX, MessageArg.DESCRIPTION),
	ADD_SUCCESS("ADD_SUCCESS"),
	ADD_ERROR("ADD_ERROR"),

	DELETE_ANNONCE("DELETE_ANNONCE",MessageArg.ID),
	DELETE_SUCCESS("DELETE_SUCCESS"),
	DELETE_ERROR("DELETE_ERROR"),

	CHECK_ALL_ANNONCES("CHECK_ALL_ANNONCES"),
	CHECK_ANNONCES_CLIENT("CHECK_ANNONCES_CLIENT", MessageArg.PSEUDO),
	CLIENT_NO_EXIST("CLIENT_NO_EXIST"),
	CHECK_ANNONCES_DOMAINE("CHECK_ANNONCES_DOMAINE", MessageArg.DOMAINE),
	DOMAINE_NO_EXIST("DOMAINE_NO_EXIST"),
	CHECK_ANNONCES_PRICE("CHECK_ANNONCES_PRICE", MessageArg.PRIX),
	PRICE_ERROR("PRICE_ERROR"),

	ANNONCES("ANNONCES", MessageArg.NB),
	ANNONCE("ANNONCE", MessageArg.ID, MessageArg.DOMAINE, MessageArg.PRIX, MessageArg.TITRE_NOSPLIT, MessageArg.PSEUDO),

	CHECK_DESCRIPTION("CHECK_DESCRIPTION", MessageArg.ID),
	DESCRIPTION("DESCRIPTION", MessageArg.DESCRIPTION),
	DESCRIPTION_VIDE("DESCRIPTION_VIDE"),
	ANNONCE_NOT_EXIST("ANNONCE_NOT_EXIST"),

	DISCONNECT("DISCONNECT"),
	DISCONNECT_SUCCESS("DISCONNECT_SUCCESS"),
	DISCONNECT_ERROR("DISCONNECT_ERROR"),

	WHOIS("WHOIS",MessageArg.PSEUDO),
	IT_IS("IT_IS",MessageArg.ADR, MessageArg.PORT),

	CALL_OPEN("CALL_OPEN", MessageArg.ADR, MessageArg.PORT , MessageArg.PSEUDO, MessageArg.ADR, MessageArg.PORT),
	CALL_OPEN_SUCCESS("CALL_OPEN_SUCCESS", MessageArg.PSEUDO),
	CALL_OPEN_ERROR("CALL_OPEN_ERROR"),

	CALL("CALL", MessageArg.PSEUDO, MessageArg.PSEUDO, MessageArg.DESCRIPTION),
	SENT("SENT"),

	CALL_CLOSE("CALL_CLOSE",MessageArg.PSEUDO, MessageArg.PSEUDO),
	CALL_CLOSE_OK("CALL_CLOSE_OK",MessageArg.PSEUDO),
	CALL_CLOSE_ERROR("CALL_CLOSE_ERROR"),

	NOPE("NOPE"),
	INVALID("INVALID"),

	QUIT("QUIT"),
	BYE("BYE");

	private final String type;
	private final MessageArg[] argsName;

	MessageType(String type, MessageArg...argsName) {
		this.type = type;
		this.argsName = argsName;
	}

	public String getType() {
		return type;
	}

	public MessageArg[] getArgsName() {
		return argsName;
	}
}
